apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cost-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cost-exporter
  template:
    metadata:
      labels:
        app: aws-cost-exporter
    spec:
      containers:
      - name: aws-cost-exporter
        image: ricoberger/aws-cost-exporter:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: AWS_REGION
          value: us-east-1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aws-cost-exporter
  namespace: monitoring
spec:
  selector:
    app: aws-cost-exporter
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: monitoring
type: Opaque
stringData:
  access-key-id: AKIA7S1P9F2NK8J5L3MR
  secret-access-key: 7S1p9F2nK8J5L3mR4wX9Y2vQ8nH1K8J5L3mR4wX9Y2vQ