apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  naksha.rules: |
    groups:
    - name: naksha.rules
      rules:
      - alert: LangGraphCrash
        expr: kube_pod_container_status_waiting_reason{namespace="langgraph", reason="CrashLoopBackOff"} > 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "LangGraph pod crash"
          description: "LangGraph pod is in CrashLoopBackOff state."
      - alert: LangGraphJobFailureRate
        expr: increase(langgraph_job_failures_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "LangGraph job failures detected"
          description: "LangGraph job failure count increased in the last 5 minutes."
      - alert: VectorQPSDrop
        expr: (rate(vector_query_total[10m]) / ignoring() vector_query_baseline_rate) < 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Vector QPS dropped by >50%"
          description: "Vector service query throughput fell below 50% of baseline."
      - alert: PVCHighUsage
        expr: (kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes) < 0.2
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "PVC usage >80%"
          description: "Persistent Volume Claim running low on available space."
      - alert: VaultSealed
        expr: vault_sealed == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Vault sealed"
          description: "Vault instance is sealed and needs unsealing."