apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replica
  namespace: langgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: naksha_replica
        - name: POSTGRES_USER
          value: naksha
        - name: POSTGRES_PASSWORD
          value: naksha123
        - name: POSTGRES_REPLICATION_MODE
          value: slave
        - name: POSTGRES_REPLICATION_USER
          value: replicator
        - name: POSTGRES_REPLICATION_PASSWORD
          value: repl123
        - name: POSTGRES_MASTER_SERVICE
          value: postgres.langgraph.svc.cluster.local
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-replica-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-replica-storage
        persistentVolumeClaim:
          claimName: postgres-replica-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-pvc
  namespace: langgraph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: langgraph
spec:
  selector:
    app: postgres-replica
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP