version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: naksha
      POSTGRES_USER: naksha
      POSTGRES_DB: naksha_system
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  hasura:
    image: hasura/graphql-engine:latest
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  minio:
    image: minio/minio
    command: server /data --console-address :9001
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    depends_on:
      - postgres
  auth:
    build: ./services/auth
    env_file: .env
    ports:
      - "9999:9999"
    depends_on:
      - postgres
  realtime:
    build: ./services/realtime
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  admin-ui:
    build: ./admin
    ports:
      - "3000:3000"
    depends_on:
      - hasura
      - auth

  langgraph:
    build: ./services/langgraph
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://naksha:naksha@postgres:5432/naksha_system
      - REDIS_URL=redis://redis:6379
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - postgres
      - redis

  vector:
    build: ./services/vector
    ports:
      - "8082:8081"
    environment:
      - MILVUS_HOST=milvus
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - milvus

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  milvus:
    image: milvusdb/milvus:v2.3.0
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

volumes:
  pgdata: {}
  miniodata: {}
  milvus_data: {}
  etcd_data: {}
