import { useState, useEffect, useRef } from 'react';
import LaunchpadLayout from '../components/LaunchpadLayout';

const Sidebar = ({ activeTab, onTabChange, onLoadTemplate, queryTabs, setQueryTabs, setActiveTabId, setSidebarTab }) => {
  return (
    <div className="w-80 bg-card/50 border-r border-border/50 h-full overflow-y-auto">
      <div className="p-4">
        <div className="flex items-center gap-2 mb-4">
          <input 
            type="text" 
            placeholder="Search queries..."
            className="flex-1 px-3 py-2 text-sm border border-border/50 rounded-lg bg-background/50 focus:outline-none focus:ring-2 focus:ring-primary/20"
          />
          <button className="p-2 hover:bg-accent/50 rounded">
            ➕
          </button>
        </div>
        
        <div className="space-y-4">
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">SHARED</h3>
            <div className="text-xs text-muted-foreground p-2">
              No shared queries
              <br />
              Share queries with your team by right-clicking on the query.
            </div>
          </div>
          
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">FAVORITES</h3>
            <div className="text-xs text-muted-foreground p-2">
              No favorite queries
              <br />
              Save a query to favorites for easy accessibility by clicking the ♡ icon.
            </div>
          </div>
          
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">PRIVATE (3)</h3>
            <div className="ml-4 space-y-1">
              {queryTabs?.filter(tab => tab.saved).map(tab => (
                <button 
                  key={tab.id} 
                  onClick={() => {
                    setActiveTabId(tab.id);
                    setSidebarTab('editor');
                  }}
                  className="flex items-center gap-2 text-sm p-1 rounded w-full text-left hover:bg-accent/20"
                >
                  <span>📄</span>
                  {tab.name}
                </button>
              ))}
            </div>
          </div>
          
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">COMMUNITY</h3>
            <div className="ml-4 space-y-1">
              <button 
                onClick={() => setSidebarTab('templates')}
                className={`flex items-center gap-2 text-sm p-1 rounded w-full text-left ${
                  activeTab === 'templates' ? 'bg-accent/50' : 'hover:bg-accent/20'
                }`}
              >
                <span>📄</span>
                Templates
              </button>
              <button 
                onClick={() => setSidebarTab('quickstarts')}
                className={`flex items-center gap-2 text-sm p-1 rounded w-full text-left ${
                  activeTab === 'quickstarts' ? 'bg-accent/50' : 'hover:bg-accent/20'
                }`}
              >
                <span>⚡</span>
                Quickstarts
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const MainContent = ({ activeTab, onUpdateQuery, onGenerate, isGenerating, generationInput, onCancelGeneration, queryTabs, setQueryTabs, setActiveTabId, setSidebarTab, handleTemplateClick, currentQueryTab }) => {
  const [queryResults, setQueryResults] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [resultTab, setResultTab] = useState('results');
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize] = useState(100);
  const [inputValue, setInputValue] = useState('');
  const [showQueryModal, setShowQueryModal] = useState(false);
  const [modalInput, setModalInput] = useState('');
  const [cursorPosition, setCursorPosition] = useState({ x: 0, y: 0 });

  const templates = {
    'Create table': `CREATE TABLE table_name (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  data JSONB,
  name TEXT
);`,
    'Add view': 'CREATE VIEW view_name AS\nSELECT column1, column2\nFROM table_name\nWHERE condition;',
    'Add column': 'ALTER TABLE table_name\nADD COLUMN column_name data_type;',
    'Add comments': 'COMMENT ON TABLE table_name IS \'Table description\';\nCOMMENT ON COLUMN table_name.column_name IS \'Column description\';',
    'Show extensions': 'SELECT * FROM pg_extension;',
    'Show version': 'SELECT version();',
    'Show active connections': 'SELECT count(*) as active_connections,\n       setting as max_connections\nFROM pg_stat_activity, pg_settings\nWHERE name = \'max_connections\';',
    'Automatically update timestamps': 'CREATE OR REPLACE FUNCTION update_updated_at_column()\nRETURNS TRIGGER AS $$\nBEGIN\n    NEW.updated_at = NOW();\n    RETURN NEW;\nEND;\n$$ language \'plpgsql\';\n\nCREATE TRIGGER update_table_updated_at\n    BEFORE UPDATE ON table_name\n    FOR EACH ROW\n    EXECUTE FUNCTION update_updated_at_column();',
    'Increment field value': 'CREATE OR REPLACE FUNCTION increment_counter()\nRETURNS TRIGGER AS $$\nBEGIN\n    NEW.counter = OLD.counter + 1;\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;',
    'pg_stat_statements report': 'SELECT query, calls, total_time, mean_time\nFROM pg_stat_statements\nORDER BY total_time DESC\nLIMIT 10;',
    'Most frequently invoked': 'SELECT query, calls\nFROM pg_stat_statements\nORDER BY calls DESC\nLIMIT 10;',
    'Most time consuming': 'SELECT query, total_time, calls, mean_time\nFROM pg_stat_statements\nORDER BY total_time DESC\nLIMIT 10;',
    'Slowest execution time': 'SELECT query, max_time, calls\nFROM pg_stat_statements\nORDER BY max_time DESC\nLIMIT 10;',
    'Hit rate': 'SELECT \n  \'index hit rate\' as name,\n  (sum(idx_blks_hit)) / sum(idx_blks_hit + idx_blks_read) as ratio\nFROM pg_statio_user_indexes\nUNION ALL\nSELECT \n  \'cache hit rate\' as name,\n  sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)) as ratio\nFROM pg_statio_user_tables;',
    'Replication status report': 'SELECT client_addr, state, sync_state, sync_priority\nFROM pg_stat_replication;'
  };

  const quickstarts = {
    'Colors': 'CREATE TABLE colors (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(50) NOT NULL,\n  hex_value VARCHAR(7) NOT NULL\n);\n\nINSERT INTO colors (name, hex_value) VALUES\n  (\'Red\', \'#FF0000\'),\n  (\'Green\', \'#00FF00\'),\n  (\'Blue\', \'#0000FF\');',
    'Todo List': 'CREATE TABLE todos (\n  id SERIAL PRIMARY KEY,\n  title VARCHAR(255) NOT NULL,\n  completed BOOLEAN DEFAULT FALSE,\n  user_id UUID REFERENCES auth.users(id),\n  created_at TIMESTAMP DEFAULT NOW()\n);\n\nALTER TABLE todos ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY "Users can view own todos" ON todos\n  FOR SELECT USING (auth.uid() = user_id);',
    'User Management': 'CREATE TABLE profiles (\n  id UUID REFERENCES auth.users(id) PRIMARY KEY,\n  username VARCHAR(50) UNIQUE,\n  full_name TEXT,\n  avatar_url TEXT,\n  created_at TIMESTAMP DEFAULT NOW()\n);\n\nALTER TABLE profiles ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY "Public profiles are viewable by everyone" ON profiles\n  FOR SELECT USING (true);',
    'Slack Clone': 'CREATE TABLE channels (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(50) NOT NULL,\n  description TEXT,\n  created_at TIMESTAMP DEFAULT NOW()\n);\n\nCREATE TABLE messages (\n  id SERIAL PRIMARY KEY,\n  content TEXT NOT NULL,\n  user_id UUID REFERENCES auth.users(id),\n  channel_id INTEGER REFERENCES channels(id),\n  created_at TIMESTAMP DEFAULT NOW()\n);'
  };



  const handleInputKeyPress = (e) => {
    if (e.key === 'Enter' && inputValue.trim()) {
      onGenerate(inputValue);
      setInputValue('');
    }
  };

  const handleModalGenerate = () => {
    if (modalInput.trim()) {
      onGenerate(modalInput);
      setShowQueryModal(false);
      setModalInput('');
    }
  };

  const executeQuery = async () => {
    if (!currentQueryTab?.query?.trim()) return;
    
    setIsLoading(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      if (activeTab.query.toLowerCase().includes('create table')) {
        setQueryResults({
          message: 'Success. No rows returned',
          rowsAffected: 0,
          executionTime: '23ms'
        });
      } else if (activeTab.query.toLowerCase().includes('select')) {
        const totalRows = 250;
        const allRows = Array.from({ length: totalRows }, (_, i) => [
          i + 1,
          `Sample Row ${i + 1}`,
          `2024-01-${String((i % 30) + 1).padStart(2, '0')} ${String((i % 24)).padStart(2, '0')}:${String((i % 60)).padStart(2, '0')}:00`
        ]);
        
        setQueryResults({
          columns: ['id', 'name', 'created_at'],
          allRows,
          totalRows,
          rowCount: totalRows,
          executionTime: '45ms'
        });
        setCurrentPage(1);
      } else {
        setQueryResults({
          message: 'Query executed successfully',
          rowsAffected: 1,
          executionTime: '23ms'
        });
      }
    } catch (error) {
      setQueryResults({ error: error.message });
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.ctrlKey && e.key === 'Enter') {
        e.preventDefault();
        executeQuery();
      }
      if (e.ctrlKey && e.key === 'q') {
        e.preventDefault();
        const textarea = document.querySelector('textarea');
        if (textarea) {
          const rect = textarea.getBoundingClientRect();
          const lines = textarea.value.substr(0, textarea.selectionStart).split('\n');
          const currentLine = lines.length - 1;
          const currentColumn = lines[lines.length - 1].length;
          
          setCursorPosition({
            x: rect.left + (currentColumn * 8) + 16,
            y: rect.top + (currentLine * 20) + 40
          });
        }
        setShowQueryModal(true);
      }
      if (e.key === 'Escape') {
        setShowQueryModal(false);
        setModalInput('');
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [currentQueryTab?.query]);
  
  if (activeTab === 'templates') {
    return (
      <div className="flex-1 p-6 bg-background/50">
        <div className="mb-6">
          <h2 className="text-2xl font-semibold mb-2">Scripts</h2>
          <p className="text-sm text-muted-foreground mb-1">
            Quick scripts to run on your database.
          </p>
          <p className="text-sm text-muted-foreground">
            Click on any script to fill the query box, modify the script, then click 'Run'.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[
            { title: 'Create table', desc: 'Basic table template. Change "table_name" to the name you prefer.', icon: '🗂️' },
            { title: 'Add view', desc: 'Template to add a view. Make sure to change the table and column names to ones that already exist.', icon: '👁️' },
            { title: 'Add column', desc: 'Template to add a column. Make sure to change the name and type.', icon: '➕' },
            { title: 'Add comments', desc: 'Templates to add a comment to either a table or a column.', icon: '💬' },
            { title: 'Show extensions', desc: 'Get a list of extensions in your database and status.', icon: '🧩' },
            { title: 'Show version', desc: 'Get your Postgres version.', icon: 'ℹ️' },
            { title: 'Show active connections', desc: 'Get the number of active and max connections.', icon: '🔗' },
            { title: 'Automatically update timestamps', desc: 'Update a column timestamp on every update.', icon: '⏰' },
            { title: 'Increment field value', desc: 'Update a field with incrementing value using stored procedure.', icon: '📈' },
            { title: 'pg_stat_statements report', desc: 'Select from pg_stat_statements and view recent queries.', icon: '📊' },
            { title: 'Most frequently invoked', desc: 'Most frequently called queries in your database.', icon: '🔥' },
            { title: 'Most time consuming', desc: 'Aggregate time spent on a query type.', icon: '⏱️' },
            { title: 'Slowest execution time', desc: 'Slowest queries based on max execution time.', icon: '🐌' },
            { title: 'Hit rate', desc: 'See your cache and index hit rate.', icon: '🎯' },
            { title: 'Replication status report', desc: 'See the status of your replication slots and replication lag.', icon: '🔄' }
          ].map((script, idx) => (
            <div 
              key={idx} 
              onClick={() => handleTemplateClick(script.title)}
              className="bg-card border border-border/50 rounded-lg p-4 hover:bg-accent/10 cursor-pointer transition-colors"
            >
              <div className="flex items-start gap-3">
                <div className="w-8 h-8 bg-muted/50 rounded flex items-center justify-center text-sm">
                  {script.icon}
                </div>
                <div className="flex-1">
                  <h3 className="font-medium text-sm mb-1">{script.title}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">{script.desc}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }
  
  if (activeTab === 'quickstarts') {
    return (
      <div className="flex-1 p-6">
        <div className="mb-6">
          <div className="flex items-center gap-4 mb-4">
            <h2 className="text-xl font-semibold">Quickstarts</h2>
            <button className="px-3 py-1 border border-border rounded text-sm">⚡ Quickstarts</button>
          </div>
          <p className="text-sm text-muted-foreground mb-4">
            Click on any script to fill the query box, modify the script, then click 'Run'.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[
            { title: 'Colors', desc: 'Create a table with a list of colors and their hex values.' },
            { title: 'Slack Clone', desc: 'Build a basic slack clone with Row Level Security.' },
            { title: 'Todo List', desc: 'Build a basic todo list with Row Level Security.' },
            { title: 'User Management', desc: 'Set up a public Profiles table which you can access with your API.' }
          ].map((script, idx) => (
            <div 
              key={idx} 
              onClick={() => {
                const template = quickstarts[script.title];
                if (template) {
                  const newId = Math.max(...queryTabs.map(t => t.id)) + 1;
                  const newTab = { id: newId, name: script.title, query: template, saved: false };
                  setQueryTabs([...queryTabs, newTab]);
                  setActiveTabId(newId);
                  setSidebarTab('editor');
                }
              }}
              className="border border-border/50 rounded-lg p-4 hover:bg-accent/10 cursor-pointer"
            >
              <div className="flex items-start gap-3">
                <span className="text-lg">⚡</span>
                <div>
                  <h3 className="font-medium mb-1">{script.title}</h3>
                  <p className="text-xs text-muted-foreground">{script.desc}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }
  
  // Default SQL Editor
  if (activeTab === 'editor' || !activeTab) {
  const [editorHeight, setEditorHeight] = useState(60); // percentage
  const [isDragging, setIsDragging] = useState(false);
  const containerRef = useRef(null);

  const handleMouseDown = (e) => {
    setIsDragging(true);
    e.preventDefault();
  };

  const handleMouseMove = (e) => {
    if (!isDragging || !containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const newHeight = ((e.clientY - rect.top) / rect.height) * 100;
    setEditorHeight(Math.max(20, Math.min(80, newHeight)));
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  useEffect(() => {
    if (isDragging) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      return () => {
        document.removeEventListener('mousemove', handleMouseMove);
        document.removeEventListener('mouseup', handleMouseUp);
      };
    }
  }, [isDragging]);

  return (
    <div ref={containerRef} className="flex-1 flex flex-col">
      {/* Main SQL Editor Area */}
      <div 
        className="flex flex-col p-4 relative bg-background/50"
        style={{ height: `${editorHeight}%` }}
      >
        
        {/* Inline AI Assistant */}
        {showQueryModal && (
          <div 
            className="absolute z-20 w-[500px]"
            style={{
              left: `${cursorPosition.x}px`,
              top: `${cursorPosition.y}px`
            }}
          >
            <div className="bg-card border border-border rounded-lg shadow-xl overflow-hidden">
              <textarea
                value={modalInput}
                onChange={(e) => setModalInput(e.target.value)}
                placeholder="Ask via the Assistant..."
                className="w-full h-20 p-3 resize-none focus:outline-none text-sm border-0"
                autoFocus
              />
              <div className="flex justify-end gap-2 p-2 bg-muted/20 border-t">
                <button
                  onClick={handleModalGenerate}
                  disabled={!modalInput.trim()}
                  className="px-3 py-1 text-sm hover:bg-accent/20 rounded disabled:opacity-50"
                >
                  Generate Enter
                </button>
                <button
                  onClick={() => {
                    setShowQueryModal(false);
                    setModalInput('');
                  }}
                  className="px-3 py-1 text-sm hover:bg-accent/20 rounded"
                >
                  Cancel Esc
                </button>
              </div>
            </div>
          </div>
        )}

        {/* AI Generation Overlay */}
        {isGenerating && (
          <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-10">
            <div className="bg-card border border-border rounded-lg p-4 shadow-lg flex items-center gap-3">
              <div className="animate-spin w-4 h-4 border-2 border-primary border-t-transparent rounded-full"></div>
              <span className="text-sm">Generating... </span>
              <button 
                onClick={onCancelGeneration}
                className="text-xs text-muted-foreground hover:text-foreground"
              >
                Cancel Esc
              </button>
            </div>
          </div>
        )}
        
        <div className="relative flex-1">
          <textarea
            value={currentQueryTab?.query || ''}
            onChange={(e) => onUpdateQuery(e.target.value)}
            className="w-full h-full p-4 bg-background/80 resize-none focus:outline-none font-mono text-sm leading-relaxed"
            placeholder="Type your query or press Ctrl+Q to generate with AI"
          />
          

        </div>
      </div>
      
      {/* Resize Handle */}
      <div 
        className="h-1 bg-border/50 hover:bg-border cursor-row-resize flex items-center justify-center group"
        onMouseDown={handleMouseDown}
      >
        <div className="w-8 h-0.5 bg-muted-foreground/50 group-hover:bg-muted-foreground transition-colors"></div>
      </div>
      
      {/* Bottom Section */}
      <div 
        className="border-t border-border/50 flex flex-col"
        style={{ height: `${100 - editorHeight}%` }}
      >
        {/* Tabs and Controls */}
        <div className="px-4 py-2 flex items-center justify-between bg-card/80 border-t border-border/30">
          <div className="flex items-center gap-4">
            <button 
              onClick={() => setResultTab('results')}
              className={`px-3 py-1 text-sm font-medium ${
                resultTab === 'results' ? 'border-b-2 border-primary text-primary' : 'hover:text-foreground'
              }`}
            >
              Results
            </button>
            <button 
              onClick={() => setResultTab('chart')}
              className={`px-3 py-1 text-sm ${
                resultTab === 'chart' ? 'border-b-2 border-primary text-primary' : 'hover:text-foreground'
              }`}
            >
              Chart
            </button>
            <button className="px-3 py-1 text-sm hover:bg-accent/20 rounded">💾</button>
            <button className="px-3 py-1 text-sm hover:bg-accent/20 rounded">♡</button>
            <button className="px-3 py-1 text-sm hover:bg-accent/20 rounded">📋</button>
            <span className="text-xs text-muted-foreground">Source</span>
            <span className="text-xs text-muted-foreground">Primary Database</span>
            <span className="text-xs text-muted-foreground">Role: postgres</span>
          </div>
          <button 
            onClick={executeQuery}
            disabled={isLoading || !currentQueryTab?.query?.trim()}
            className="px-4 py-1 bg-primary text-primary-foreground rounded text-sm hover:bg-primary/90 transition-colors disabled:opacity-50"
          >
            {isLoading ? 'Running...' : 'Run CTRL ↵'}
          </button>
        </div>
        
        {/* Results Area */}
        <div className="p-4 flex-1 overflow-y-auto">
          {!queryResults ? (
            <div className="text-center py-12 text-muted-foreground">
              <p className="text-sm">Click Run to execute your query.</p>
            </div>
          ) : resultTab === 'results' ? (
            <div>
              {queryResults.error ? (
                <div className="text-red-500 text-sm">
                  <strong>Error:</strong> {queryResults.error}
                </div>
              ) : queryResults.columns ? (
                <div>
                  {(() => {
                    const startIdx = (currentPage - 1) * pageSize;
                    const endIdx = startIdx + pageSize;
                    const currentRows = queryResults.allRows?.slice(startIdx, endIdx) || queryResults.rows || [];
                    const totalPages = Math.ceil((queryResults.totalRows || queryResults.rowCount) / pageSize);
                    
                    return (
                      <>
                        <div className="flex items-center justify-between mb-2">
                          <div className="text-xs text-muted-foreground">
                            {queryResults.rowCount} rows • {queryResults.executionTime}
                          </div>
                          {totalPages > 1 && (
                            <div className="flex items-center gap-2 text-xs">
                              <span className="text-muted-foreground">
                                {startIdx + 1}-{Math.min(endIdx, queryResults.totalRows || queryResults.rowCount)} of {queryResults.totalRows || queryResults.rowCount}
                              </span>
                              <button 
                                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                                disabled={currentPage === 1}
                                className="px-2 py-1 border rounded disabled:opacity-50 hover:bg-accent/20"
                              >
                                ←
                              </button>
                              <span className="px-2">{currentPage} / {totalPages}</span>
                              <button 
                                onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                                disabled={currentPage === totalPages}
                                className="px-2 py-1 border rounded disabled:opacity-50 hover:bg-accent/20"
                              >
                                →
                              </button>
                            </div>
                          )}
                        </div>
                        <div className="overflow-x-auto">
                          <table className="w-full text-sm border border-border/50">
                            <thead>
                              <tr className="bg-muted/50">
                                {queryResults.columns.map((col, idx) => (
                                  <th key={idx} className="px-3 py-2 text-left border-b border-border/50">
                                    {col}
                                  </th>
                                ))}
                              </tr>
                            </thead>
                            <tbody>
                              {currentRows.map((row, idx) => (
                                <tr key={startIdx + idx} className="hover:bg-muted/20">
                                  {row.map((cell, cellIdx) => (
                                    <td key={cellIdx} className="px-3 py-2 border-b border-border/20">
                                      {cell}
                                    </td>
                                  ))}
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </>
                    );
                  })()
                  }
                </div>
              ) : (
                <div className="text-green-600 text-sm">
                  <div>{queryResults.message}</div>
                  <div className="text-xs text-muted-foreground mt-1">
                    {queryResults.rowsAffected !== undefined ? `${queryResults.rowsAffected} rows affected • ` : ''}{queryResults.executionTime}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="text-center py-12 text-muted-foreground">
              <p className="text-sm">Chart visualization not implemented yet.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
  }
};

export default function SQLEditor() {
  const [sidebarTab, setSidebarTab] = useState('editor');
  const [queryTabs, setQueryTabs] = useState([
    { id: 1, name: 'Create table', query: 'CREATE TABLE table_name (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  name TEXT\n);', saved: true },
    { id: 2, name: 'OpenAI Vector Search', query: 'SELECT * FROM documents\nWHERE embedding <-> $1 < 0.5\nORDER BY embedding <-> $1\nLIMIT 10;', saved: true },
    { id: 3, name: 'Untitled', query: '', saved: false }
  ]);
  const [activeTabId, setActiveTabId] = useState(3);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationInput, setGenerationInput] = useState('');

  const activeTab = queryTabs.find(tab => tab.id === activeTabId);

  const handleLoadTemplate = () => {
    setSidebarTab('editor');
  };

  const handleTemplateClick = (title, isQuickstart = false) => {
    const templates = {
      'Create table': `CREATE TABLE table_name (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  data JSONB,
  name TEXT
);`,
      'Add view': 'CREATE VIEW view_name AS\nSELECT column1, column2\nFROM table_name\nWHERE condition;',
      'Add column': 'ALTER TABLE table_name\nADD COLUMN column_name data_type;',
      'Add comments': 'COMMENT ON TABLE table_name IS \'Table description\';\nCOMMENT ON COLUMN table_name.column_name IS \'Column description\';',
      'Show extensions': 'SELECT * FROM pg_extension;',
      'Show version': 'SELECT version();',
      'Show active connections': 'SELECT count(*) as active_connections FROM pg_stat_activity;',
      'Automatically update timestamps': 'CREATE OR REPLACE FUNCTION update_updated_at_column()\nRETURNS TRIGGER AS $$\nBEGIN\n    NEW.updated_at = NOW();\n    RETURN NEW;\nEND;\n$$ language \'plpgsql\';',
      'Increment field value': 'CREATE OR REPLACE FUNCTION increment_counter()\nRETURNS TRIGGER AS $$\nBEGIN\n    NEW.counter = OLD.counter + 1;\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;',
      'pg_stat_statements report': 'SELECT query, calls, total_time FROM pg_stat_statements ORDER BY total_time DESC LIMIT 10;',
      'Most frequently invoked': 'SELECT query, calls FROM pg_stat_statements ORDER BY calls DESC LIMIT 10;',
      'Most time consuming': 'SELECT query, total_time FROM pg_stat_statements ORDER BY total_time DESC LIMIT 10;',
      'Slowest execution time': 'SELECT query, max_time FROM pg_stat_statements ORDER BY max_time DESC LIMIT 10;',
      'Hit rate': 'SELECT \'cache hit rate\' as name, sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)) as ratio FROM pg_statio_user_tables;',
      'Replication status report': 'SELECT client_addr, state, sync_state FROM pg_stat_replication;'
    };

    const quickstarts = {
      'Colors': 'CREATE TABLE colors (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(50) NOT NULL,\n  hex_value VARCHAR(7) NOT NULL\n);\n\nINSERT INTO colors (name, hex_value) VALUES (\'Red\', \'#FF0000\');',
      'Todo List': 'CREATE TABLE todos (\n  id SERIAL PRIMARY KEY,\n  title VARCHAR(255) NOT NULL,\n  completed BOOLEAN DEFAULT FALSE\n);',
      'User Management': 'CREATE TABLE profiles (\n  id UUID PRIMARY KEY,\n  username VARCHAR(50) UNIQUE,\n  full_name TEXT\n);',
      'Slack Clone': 'CREATE TABLE channels (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(50) NOT NULL\n);'
    };

    const template = isQuickstart ? quickstarts[title] : templates[title];
    if (template) {
      const newId = Math.max(...queryTabs.map(t => t.id)) + 1;
      const newTab = { id: newId, name: title, query: template, saved: false };
      setQueryTabs([...queryTabs, newTab]);
      setActiveTabId(newId);
      setSidebarTab('editor');
    }
  };

  const addNewTab = () => {
    const newId = Math.max(...queryTabs.map(t => t.id)) + 1;
    const untitledCount = queryTabs.filter(t => t.name.startsWith('Untitled')).length;
    const name = untitledCount === 0 ? 'Untitled' : `Untitled-${untitledCount + 1}`;
    const newTab = { id: newId, name, query: '', saved: false };
    setQueryTabs([...queryTabs, newTab]);
    setActiveTabId(newId);
  };

  const closeTab = (tabId) => {
    const newTabs = queryTabs.filter(tab => tab.id !== tabId);
    setQueryTabs(newTabs);
    
    if (activeTabId === tabId) {
      const remainingTab = newTabs[newTabs.length - 1] || newTabs[0];
      setActiveTabId(remainingTab?.id);
    }
  };

  const updateTabQuery = (query) => {
    setQueryTabs(tabs => tabs.map(tab => {
      if (tab.id === activeTabId) {
        // Auto-generate tab name from query
        let newName = tab.name;
        if (query.trim() && (tab.name.startsWith('Untitled') || tab.name === 'New')) {
          const firstLine = query.split('\n')[0].trim();
          if (firstLine.toLowerCase().startsWith('select')) {
            newName = 'Query';
          } else if (firstLine.toLowerCase().startsWith('create table')) {
            const match = firstLine.match(/create table\s+(\w+)/i);
            newName = match ? `Create ${match[1]}` : 'Create table';
          } else if (firstLine.toLowerCase().startsWith('insert')) {
            newName = 'Insert data';
          } else if (firstLine.toLowerCase().startsWith('update')) {
            newName = 'Update data';
          } else if (firstLine.toLowerCase().startsWith('delete')) {
            newName = 'Delete data';
          } else {
            newName = firstLine.substring(0, 20) + (firstLine.length > 20 ? '...' : '');
          }
        }
        return { ...tab, query, name: newName, saved: false };
      }
      return tab;
    }));
  };

  const handleGenerate = async (input) => {
    if (!input.trim()) return;
    
    setIsGenerating(true);
    setGenerationInput(input);
    
    try {
      await new Promise(resolve => setTimeout(resolve, 2000));
      const generatedQuery = `-- Generated query for: ${input}\nSELECT * FROM ${input.toLowerCase().replace(/\s+/g, '_')}\nWHERE created_at > NOW() - INTERVAL '1 day'\nORDER BY created_at DESC;`;
      updateTabQuery(generatedQuery);
    } finally {
      setIsGenerating(false);
      setGenerationInput('');
    }
  };

  return (
    <LaunchpadLayout>
      <div className="h-screen flex bg-muted/10">
        <Sidebar 
          activeTab={sidebarTab}
          onTabChange={setSidebarTab}
          onLoadTemplate={handleLoadTemplate}
          queryTabs={queryTabs}
          setQueryTabs={setQueryTabs}
          setActiveTabId={setActiveTabId}
          setSidebarTab={setSidebarTab}
        />
        <div className="flex-1 flex flex-col">
          {/* Query Tabs */}
          <div className="flex items-center bg-card/80 border-b border-border/50">
            {queryTabs.map(tab => (
              <div
                key={tab.id}
                className={`flex items-center border-r border-border/50 ${
                  tab.id === activeTabId 
                    ? 'bg-primary/10 text-primary border-b-2 border-b-primary' 
                    : 'text-muted-foreground hover:text-foreground hover:bg-accent/20'
                }`}
              >
                <button
                  onClick={() => setActiveTabId(tab.id)}
                  className="px-4 py-2 text-sm flex-1 text-left font-medium"
                  title={tab.query ? tab.query.split('\n')[0] : 'Empty query'}
                >
                  {tab.name}
                  {!tab.saved && ' •'}
                </button>
                {queryTabs.length > 1 && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      closeTab(tab.id);
                    }}
                    className="px-2 py-2 text-xs hover:bg-red-500/20 hover:text-red-500"
                  >
                    ×
                  </button>
                )}
              </div>
            ))}
            <button 
              onClick={addNewTab}
              className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-accent/20"
            >
              +
            </button>
          </div>
          
          <MainContent 
            activeTab={sidebarTab}
            onUpdateQuery={updateTabQuery}
            onGenerate={handleGenerate}
            isGenerating={isGenerating}
            generationInput={generationInput}
            onCancelGeneration={() => setIsGenerating(false)}
            queryTabs={queryTabs}
            setQueryTabs={setQueryTabs}
            setActiveTabId={setActiveTabId}
            setSidebarTab={setSidebarTab}
            handleTemplateClick={handleTemplateClick}
            currentQueryTab={activeTab}
          />
        </div>
      </div>
    </LaunchpadLayout>
  );
}