apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph
  namespace: langgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langgraph
  template:
    metadata:
      labels:
        app: langgraph
    spec:
      containers:
      - name: langgraph
        image: naksha/langgraph:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://naksha:naksha@postgres:5432/naksha_system"
        - name: REDIS_URL
          value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: langgraph
  namespace: langgraph
spec:
  selector:
    app: langgraph
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP