apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-data-pvc
  namespace: vector
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: hostpath