apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vector-hpa
  namespace: vector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vector
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65