apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph
  labels:
    app: langgraph
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langgraph
  template:
    metadata:
      labels:
        app: langgraph
    spec:
      serviceAccountName: langgraph-sa
      containers:
        - name: langgraph
          image: naksha/langgraph:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: url
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: VAULT_ADDR
              value: "http://vault:8200"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080