replicaCount: 2

image:
  repository: naksha/langgraph
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: langgraph.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: url
  - name: REDIS_URL
    value: "redis://redis:6379"
  - name: VAULT_ADDR
    value: "http://vault:8200"
  - name: VAULT_ROLE
    value: "langgraph-role"

serviceAccount:
  create: true
  name: langgraph-sa