server:
  persistentVolume:
    enabled: true
    size: 20Gi
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrapeConfigs:
  - job_name: 'langgraph'
    static_configs:
      - targets: ['langgraph:8080']
    metrics_path: '/metrics'
  
  - job_name: 'vector-service'
    static_configs:
      - targets: ['vector:8081']
    metrics_path: '/metrics'
  
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 2Gi